version: '3.9'

services:
  thelounge:
    container_name: thelounge
    image: lscr.io/linuxserver/thelounge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /data/thelounge/config:/config
    ports:
      - 9001:9000
    restart: unless-stopped